<script setup lang="ts">
import { computed, ref } from "vue"; import { useMutation, useQuery, useQueryClient } from "@tanstack/vue-query"; import { RouterLink } from "vue-router"; import { api } from "@/api/http"; import type { TaskSummary } from "@/api/types"; import StatusBadge from "@/components/StatusBadge.vue";
const queryClient=useQueryClient(); const search=ref(""); const stage=ref("");
const tasks=useQuery({queryKey:["tasks"],queryFn:()=>api<TaskSummary[]>("/api/tasks"),refetchInterval:8000});
const filtered=computed(()=>(tasks.data.value||[]).filter(t=>(!search.value||t.theme.toLowerCase().includes(search.value.toLowerCase())||t.task_id.includes(search.value))&&(!stage.value||t.stage===stage.value)));
const remove=useMutation({mutationFn:(id:string)=>api(`/api/tasks/${id}`,{method:"DELETE"}),onSuccess:()=>queryClient.invalidateQueries({queryKey:["tasks"]})});
function deleteTask(task:TaskSummary){if(confirm(`删除任务“${task.theme}”？该操作不可恢复。`))remove.mutate(task.task_id)}
</script>
<template><div class="page-stack"><header class="page-header"><div><h1>任务</h1><p>任务是材料、分析、报告与版本记录的业务容器。</p></div><RouterLink class="btn primary" to="/?create=1">新建任务</RouterLink></header><section class="surface"><div class="filters"><input v-model="search" placeholder="搜索任务名称或 ID"/><select v-model="stage"><option value="">全部状态</option><option value="created">待运行</option><option value="writing">报告生成</option><option value="review">待审核</option><option value="done">已完成</option><option value="failed">异常</option></select></div><div v-if="tasks.isLoading.value" class="loading-line"></div><div v-if="filtered.length" class="data-list"><div v-for="task in filtered" :key="task.task_id" class="data-row task-line"><RouterLink :to="`/tasks/${task.task_id}`"><strong>{{ task.theme }}</strong><small class="mono">{{ task.task_id }}</small></RouterLink><span>{{ task.material_count || 0 }} 份材料</span><span>{{ task.updated_at || task.created_at || '—' }}</span><StatusBadge :stage="task.stage"/><div class="button-row"><RouterLink class="btn tertiary" :to="`/tasks/${task.task_id}`">打开</RouterLink><button class="btn tertiary danger" @click="deleteTask(task)">删除</button></div></div></div><div v-else-if="!tasks.isLoading.value" class="empty"><div><strong>没有匹配的任务</strong>调整筛选条件或新建任务。</div></div></section></div></template>
<style scoped>.filters{display:grid;grid-template-columns:minmax(260px,1fr) 180px;gap:12px;padding:16px}.task-line{grid-template-columns:minmax(260px,1fr) 90px 150px auto auto}.task-line strong,.task-line small{display:block}.task-line small{font-size:11px;color:var(--color-faint);margin-top:2px}@media(max-width:900px){.task-line{grid-template-columns:1fr auto}.task-line>span:nth-of-type(-n+2){display:none}}@media(max-width:600px){.filters{grid-template-columns:1fr}}</style>
