<script setup lang="ts">
import { ref } from "vue"; import { useMutation,useQuery,useQueryClient } from "@tanstack/vue-query"; import { api,jsonInit } from "@/api/http";
const qc=useQueryClient();const upload=ref<HTMLInputElement>();const selected=ref<any>(null);const schema=ref<any>(null);const error=ref("");
const variants=useQuery({queryKey:["templates"],queryFn:()=>api<any[]>("/api/style/variants")});
const analyze=useMutation({mutationFn:()=>{const fd=new FormData();for(const file of upload.value?.files||[])fd.append("files",file);return api("/api/style/analyze",{method:"POST",body:fd})},onSuccess:()=>qc.invalidateQueries({queryKey:["templates"]}),onError:e=>error.value=e instanceof Error?e.message:"学习失败"});
const action=useMutation({mutationFn:({id,op}:{id:number;op:string})=>api(`/api/style/variants/${id}${op==='delete'?'':`/${op}`}`,{method:op==='delete'?"DELETE":"POST"}),onSuccess:()=>qc.invalidateQueries({queryKey:["templates"]})});
async function inspect(item:any){selected.value=item;schema.value=null;try{schema.value=await api(`/api/style/variants/${item.id}/template-schema`)}catch{schema.value={error:"该模板暂无结构化 Schema"}}}
function remove(item:any){if(confirm(`删除模板“${item.name||item.label||item.id}”？`))action.mutate({id:item.id,op:"delete"})}
function role(schema:any,key:string){return schema?.roles?.[key]||schema?.styles?.[key]||schema?.[key]||{}}
function format(value:any){if(!value||typeof value!=="object")return "尚未识别";const font=value.font?.name||value.font_name||value.font||"字体未定";const size=value.font?.size_pt||value.size_pt||value.size||"";const align=value.paragraph?.alignment||value.alignment||"";return [font,size?`${size}pt`:"",align].filter(Boolean).join(" / ")}
</script>
<template><div class="page-stack"><header class="page-header"><div><h1>模板中心</h1><p>模板决定呈现方式；内容结构是否受约束由模板类型明确表达。</p></div></header><section class="surface upload-bar"><div><h2>学习 Word 模板</h2><p class="muted">保留原始 DOCX，同时生成可检查的结构化模板 Schema。</p></div><input ref="upload" type="file" accept=".docx" multiple/><button class="btn primary" :disabled="analyze.isPending.value" @click="analyze.mutate()">{{analyze.isPending.value?'正在学习…':'上传并学习'}}</button><span v-if="error" class="error-text">{{error}}</span></section><section class="template-layout"><div class="surface templates"><div class="section-head"><div><h2>文档模板</h2><p class="muted">字体、标题层级、编号、页面和段落格式</p></div></div><div v-if="variants.data.value?.length" class="template-grid"><article v-for="item in variants.data.value" :key="item.id" class="template-item" @click="inspect(item)"><div class="paper-preview"><span></span><span></span><span></span><span></span></div><div class="template-meta"><div><strong>{{item.name||item.label||`模板 ${item.id}`}}</strong><p>{{item.description||'Word 文档模板'}}</p></div><div class="button-row"><span v-if="item.locked" class="badge success">默认</span><span v-else-if="item.confirmed" class="badge">可用</span><button v-if="!item.confirmed" class="btn tertiary" @click.stop="action.mutate({id:item.id,op:'confirm'})">确认</button><button v-if="!item.locked" class="btn tertiary" @click.stop="action.mutate({id:item.id,op:'lock'})">设为默认</button><button class="btn tertiary danger" @click.stop="remove(item)">删除</button></div></div></article></div><div v-else class="empty"><div><strong>暂无文档模板</strong>上传 DOCX 后可查看模板学习结果。</div></div></div><aside class="surface schema-panel"><template v-if="selected"><small>结构化模板</small><h2>{{selected.name||selected.label}}</h2><p class="muted">以下内容直接来自模板学习结果，用于定位识别与导出之间的偏差。</p><div class="schema-list"><div><span>主标题</span><b>{{format(role(schema,'document_title'))}}</b></div><div><span>一级标题</span><b>{{format(role(schema,'heading_1'))}}</b></div><div><span>二级标题</span><b>{{format(role(schema,'heading_2'))}}</b></div><div><span>三级标题</span><b>{{format(role(schema,'heading_3'))}}</b></div><div><span>正文</span><b>{{format(role(schema,'body'))}}</b></div></div><details><summary>查看完整 Schema</summary><pre>{{JSON.stringify(schema,null,2)}}</pre></details></template><div v-else class="empty"><div><strong>选择一个模板</strong>查看标题层级、字体、编号和页面设置。</div></div></aside></section></div></template>
<style scoped>.upload-bar{display:grid;grid-template-columns:minmax(280px,1fr) minmax(260px,420px) auto;align-items:center;gap:16px;padding:20px 24px}.upload-bar h2,.upload-bar p{margin-bottom:2px}.template-layout{display:grid;grid-template-columns:minmax(0,1fr) 390px;gap:24px}.templates,.schema-panel{padding:24px}.template-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:16px}.template-item{display:grid;grid-template-columns:78px 1fr;gap:14px;padding:14px;border:1px solid var(--color-border);background:#fff;cursor:pointer}.template-item:hover{border-color:#b7c4d3}.paper-preview{width:72px;height:96px;padding:14px 10px;background:#fff;border:1px solid #d7dbe0;box-shadow:0 2px 7px rgba(30,40,52,.08)}.paper-preview span{display:block;height:2px;margin-bottom:9px;background:#cfd5dc}.paper-preview span:first-child{width:70%;height:4px;margin-inline:auto;background:#52677e}.template-meta{min-width:0}.template-meta strong{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.template-meta p{min-height:36px;color:var(--color-muted);font-size:12px}.template-meta .button-row{gap:3px}.template-meta .btn{min-height:28px;padding:2px 6px;font-size:11px}.schema-panel small{color:var(--color-faint)}.schema-list{margin:20px 0;border-top:1px solid var(--color-border)}.schema-list>div{display:grid;grid-template-columns:80px 1fr;gap:12px;padding:12px 0;border-bottom:1px solid var(--color-border)}.schema-list span{color:var(--color-muted)}.schema-list b{font-weight:500}.schema-panel pre{max-height:300px;overflow:auto;white-space:pre-wrap;font-size:11px}@media(max-width:1050px){.template-layout{grid-template-columns:1fr}.upload-bar{grid-template-columns:1fr auto}.upload-bar>div{grid-column:1/-1}}@media(max-width:650px){.upload-bar{grid-template-columns:1fr}.template-grid{grid-template-columns:1fr}}</style>
